# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "llm.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tllm.proto\x12\x0bluckystonks"G\n\x11GetInsightRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t"5\n\x0fGetInsightReply\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t2U\n\x07Insight\x12J\n\nGetInsight\x12\x1e.luckystonks.GetInsightRequest\x1a\x1c.luckystonks.GetInsightReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETINSIGHTREQUEST"]._serialized_start = 26
    _globals["_GETINSIGHTREQUEST"]._serialized_end = 97
    _globals["_GETINSIGHTREPLY"]._serialized_start = 99
    _globals["_GETINSIGHTREPLY"]._serialized_end = 152
    _globals["_INSIGHT"]._serialized_start = 154
    _globals["_INSIGHT"]._serialized_end = 239
# @@protoc_insertion_point(module_scope)
