# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x0bluckystonks\"k\n\x12RequestVoteRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x0c\n\x04term\x18\x03 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x04 \x01(\x03\x12\x15\n\rlast_log_term\x18\x05 \x01(\x03\"P\n\x10RequestVoteReply\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x0c\n\x04term\x18\x03 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x04 \x01(\x08\"\xa3\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x0c\n\x04term\x18\x03 \x01(\x03\x12\x12\n\nprev_index\x18\x04 \x01(\x03\x12\x11\n\tprev_term\x18\x05 \x01(\x03\x12\x14\n\x0c\x63ommit_index\x18\x06 \x01(\x03\x12&\n\x07\x65ntries\x18\x07 \x03(\x0b\x32\x15.luckystonks.LogEntry\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\x0c\"i\n\x12\x41ppendEntriesReply\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x0c\n\x04term\x18\x03 \x01(\x03\x12\x16\n\x0e\x65ntry_appended\x18\x04 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x05 \x01(\x03\x32\xaa\x01\n\x04Raft\x12M\n\x0bRequestVote\x12\x1f.luckystonks.RequestVoteRequest\x1a\x1d.luckystonks.RequestVoteReply\x12S\n\rAppendEntries\x12!.luckystonks.AppendEntriesRequest\x1a\x1f.luckystonks.AppendEntriesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=27
  _globals['_REQUESTVOTEREQUEST']._serialized_end=134
  _globals['_REQUESTVOTEREPLY']._serialized_start=136
  _globals['_REQUESTVOTEREPLY']._serialized_end=216
  _globals['_APPENDENTRIESREQUEST']._serialized_start=219
  _globals['_APPENDENTRIESREQUEST']._serialized_end=382
  _globals['_LOGENTRY']._serialized_start=384
  _globals['_LOGENTRY']._serialized_end=425
  _globals['_APPENDENTRIESREPLY']._serialized_start=427
  _globals['_APPENDENTRIESREPLY']._serialized_end=532
  _globals['_RAFT']._serialized_start=535
  _globals['_RAFT']._serialized_end=705
# @@protoc_insertion_point(module_scope)
